### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by antoine4ucsd** [kodaim1115/CYBERTRACK2#2]
Hello
I am very interested in your package to analyze longitudinal flow data but I am having issue installing it. 
I am using
``
devtools::install_github("kodaim1115/CYBERTRACK2")
``

but it leads to fatal error
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:211:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [CYBERTRACK2.o] Error 1
ERROR: compilation failed for package ‘CYBERTRACK2’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/CYBERTRACK2’
Error: Failed to install 'CYBERTRACK2' from GitHub:
  (converted from warning) installation of package ‘/var/folders/r3/y359df552hg8krxm_3lr1f1r0000gr/T//RtmpzGWoav/file21d8c8fb3ea/CYBERTRACK2_1.0.tar.gz’ had non-zero exit status

I am using R version 4.0.3

thank you!

**Comment by kodaim1115** [comment]
Thank you very much for having an interest in my package.
I will look into the problem.

**Comment by kodaim1115** [comment]
Seems like you need to use complier c++11 or up.
These URLs may be helpful.
https://stackoverflow.com/questions/45047508/error-unknown-type-name-constexpr-during-make-in-mac-os-x
https://stackoverflow.com/questions/61590047/error-unknown-type-name-constexpr-when-compiling-using-g-on-mac?noredirect=1&lq=1
